# Generated by Django 5.2.7 on 2025-11-06 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='chat_conver_updated_1f6ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-timestamp'], name='chat_messag_convers_dca7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sender'], name='chat_messag_convers_4b66ea_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'is_read'], name='chat_messag_user_id_7c6d14_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'user'], name='chat_messag_message_c98ef4_idx'),
        ),
    ]
