"""
Django settings for ripple project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-w4er*aj_!(usv$t#i5561ihfz^+hl&)ri6ul*-)be7c_1c_hu0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Allow connections from localhost and any local network IP
# This automatically works on any WiFi network
import socket
def get_local_ip():
    """Get the local IP address of this machine"""
    try:
        # Connect to a remote address to determine local IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except:
        return '127.0.0.1'

# Production: Use ALLOWED_HOSTS from environment
# Development: Use localhost and local IP
if DEBUG:
    LOCAL_IP = get_local_ip()
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', LOCAL_IP]
    # Print the IP for easy access
    try:
        print(f"\n{'='*60}")
        print(f"Server accessible at: http://{LOCAL_IP}:8000")
        print(f"Use this IP on other devices (same WiFi)")
        print(f"{'='*60}\n")
    except UnicodeEncodeError:
        # Fallback for systems with encoding issues
        print(f"\n{'='*60}")
        print(f"Server accessible at: http://{LOCAL_IP}:8000")
        print(f"Use this IP on other devices (same WiFi)")
        print(f"{'='*60}\n")
else:
    # Production: Parse ALLOWED_HOSTS from environment
    allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '')
    ALLOWED_HOSTS = []
    
    # Add hosts from environment variable
    if allowed_hosts_str:
        ALLOWED_HOSTS.extend([host.strip() for host in allowed_hosts_str.split(',') if host.strip()])
    
    # Always include localhost for health checks
    if 'localhost' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('localhost')
    if '127.0.0.1' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('127.0.0.1')
    
    # Add Railway domain - check multiple possible environment variables
    railway_domain = (
        os.getenv('RAILWAY_PUBLIC_DOMAIN') or 
        os.getenv('RAILWAY_STATIC_URL') or 
        'rippleskillshare.up.railway.app'
    )
    # Extract domain from URL if it's a full URL
    if railway_domain and (railway_domain.startswith('http://') or railway_domain.startswith('https://')):
        from urllib.parse import urlparse
        railway_domain = urlparse(railway_domain).netloc
    # Add the Railway domain
    if railway_domain and railway_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(railway_domain)

# Always add Railway domain if DATABASE_URL is set (indicates production on Railway)
# This ensures the domain is added even if DEBUG=True
if os.getenv('DATABASE_URL'):
    railway_domain = (
        os.getenv('RAILWAY_PUBLIC_DOMAIN') or 
        os.getenv('RAILWAY_STATIC_URL') or 
        'rippleskillshare.up.railway.app'
    )
    if railway_domain:
        # Extract domain from URL if it's a full URL
        if railway_domain.startswith('http://') or railway_domain.startswith('https://'):
            from urllib.parse import urlparse
            railway_domain = urlparse(railway_domain).netloc
        # Add the Railway domain to ALLOWED_HOSTS if not already present
        if railway_domain not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(railway_domain)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'users',
    'skills',
    'communities',
    'chat',
    'skill_admin', 
    # email auth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # email auth
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'ripple.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.recaptcha_site_key',
            ],
        },
    },
]

WSGI_APPLICATION = 'ripple.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL in production (via DATABASE_URL), SQLite in development
DATABASE_URL = os.getenv('DATABASE_URL', '').strip()

# Only use PostgreSQL if DATABASE_URL is a non-empty string that starts with a database scheme
if DATABASE_URL and (DATABASE_URL.startswith('postgresql://') or DATABASE_URL.startswith('postgres://')):
    # Production: Use PostgreSQL on Railway
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,  # Require SSL for Railway PostgreSQL
        )
    }
else:
    # Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media (user uploads)
MEDIA_URL = 'media/'

# Use Railway volume if available, otherwise use project directory
# Railway volumes are mounted at /data by default
RAILWAY_VOLUME_MOUNT_PATH = os.getenv('RAILWAY_VOLUME_MOUNT_PATH', '/data')
if os.path.exists(RAILWAY_VOLUME_MOUNT_PATH):
    # Use Railway volume for persistent storage
    MEDIA_ROOT = Path(RAILWAY_VOLUME_MOUNT_PATH) / 'media'
else:
    # Fallback to project directory (ephemeral - files lost on redeploy)
    MEDIA_ROOT = BASE_DIR / 'media'

# Ensure media directory exists
try:
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
except (OSError, PermissionError):
    pass  # Directory might already exist or permissions issue

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Email settings - SendGrid only
USE_CONSOLE_EMAIL = os.getenv('USE_CONSOLE_EMAIL', '').lower() == 'true'

# Check for SendGrid API key
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')

# Use SendGrid if API key is provided and console email is NOT explicitly enabled
if SENDGRID_API_KEY and not USE_CONSOLE_EMAIL:
    # Use SendGrid Web API (faster and more reliable than SMTP)
    EMAIL_BACKEND = 'ripple.email_backends.SendGridBackend'
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@ripple.com')
    
    # Always log email configuration (without exposing API key)
    print(f"\n{'='*60}")
    print(f"Email Configuration:")
    print(f"  Backend: SendGrid Web API")
    print(f"  From Email: {DEFAULT_FROM_EMAIL}")
    print(f"  API Key: Set and configured")
    print(f"  Status: SendGrid is configured and ready to send emails")
    print(f"{'='*60}\n")
else:
    # For development: emails will be printed to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@ripple.com'
    # Always log email configuration
    print(f"\n{'='*60}")
    print(f"Email Configuration: Console Backend (Development Mode)")
    print(f"  Backend: Console Email Backend")
    print(f"  From Email: {DEFAULT_FROM_EMAIL}")
    print(f"  Status: Emails will be printed to console, not sent")
    if not SENDGRID_API_KEY:
        print(f"  Warning: SENDGRID_API_KEY not set!")
    if USE_CONSOLE_EMAIL:
        print(f"  Note: USE_CONSOLE_EMAIL is explicitly enabled")
    print(f"{'='*60}\n")

# AllAuth settings
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Enable email verification for regular signups
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_USERNAME_MIN_LENGTH = 3

# Social account settings - skip email verification since Google already verified it
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Don't require email verification for social accounts
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create account on social login
SOCIALACCOUNT_EMAIL_REQUIRED = False  # Don't require email for social accounts (Google provides it)
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from Google OAuth

# New AllAuth settings format
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 attempts per 5 minutes
}

# Password reset settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours

STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')

# Site ID for allauth (required for social accounts)
SITE_ID = 1

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
        }
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = True

# Google reCAPTCHA settings
RECAPTCHA_SITE_KEY = os.getenv('RECAPTCHA_SITE_KEY', '')
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '')

# Custom adapters to handle email verification
SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'

# Redirect cancelled/error social logins back to login page
SOCIALACCOUNT_LOGIN_CANCELLED_URL = '/users/login/'
SOCIALACCOUNT_LOGIN_ERROR_URL = '/users/login/'

# CSRF Trusted Origins - Required for CSRF verification
CSRF_TRUSTED_ORIGINS = []
if os.getenv('DATABASE_URL'):  # On Railway (production)
    railway_domain = (
        os.getenv('RAILWAY_PUBLIC_DOMAIN') or 
        os.getenv('RAILWAY_STATIC_URL') or 
        'rippleskillshare.up.railway.app'
    )
    if railway_domain:
        # Extract domain from URL if it's a full URL
        if railway_domain.startswith('http://') or railway_domain.startswith('https://'):
            from urllib.parse import urlparse
            railway_domain = urlparse(railway_domain).netloc
        # Add both HTTP and HTTPS versions
        CSRF_TRUSTED_ORIGINS.extend([
            f'https://{railway_domain}',
            f'http://{railway_domain}',  # Allow HTTP for Railway internal routing
        ])
elif DEBUG:
    # Development: allow localhost
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]

# Production Security Settings
if not DEBUG:
    # HTTPS/SSL Settings
    # Railway handles SSL termination, so we don't redirect here
    # Set SECURE_SSL_REDIRECT=False in Railway if you get redirect loops
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    
    # Trust Railway's proxy for SSL
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # In production, only use secure cookies if we're actually on HTTPS
    # Railway uses HTTPS, but the request might come through as HTTP internally
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development: use insecure cookies for easier testing
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
