# Generated by Django 5.2.7 on 2025-10-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='verification_message',
            field=models.TextField(blank=True, help_text='Message from admin about verification status'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the evidence', max_length=200)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('image', 'Image'), ('link', 'Link')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload a file (document, video, image)', null=True, upload_to='skill_evidence/')),
                ('link', models.URLField(blank=True, help_text='Or provide a link to your work/portfolio')),
                ('description', models.TextField(blank=True, help_text='Describe what this evidence demonstrates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary evidence for this skill')),
                ('user_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='skills.userskill')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
