# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_userskill_created_at_userskill_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='teacher_applications/')),
                ('portfolio_links', models.TextField(blank=True, help_text='Comma or newline separated links')),
                ('expertise_topics', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_teacher_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeachingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('full_description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Price in cents (e.g., 1999 = $19.99)')),
                ('is_tradeable', models.BooleanField(default=False)),
                ('trade_notes', models.CharField(blank=True, max_length=200)),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='class_intros/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='class_thumbs/')),
                ('is_published', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassTradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_class_trades', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_class_trades', to=settings.AUTH_USER_MODEL)),
                ('offered_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='skills.teachingclass')),
                ('requested_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='skills.teachingclass')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('teaching_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='skills.teachingclass')),
            ],
        ),
        migrations.CreateModel(
            name='ClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reviews', to=settings.AUTH_USER_MODEL)),
                ('teaching_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skills.teachingclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('teaching_class', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('refunded', 'Refunded'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('granted_via', models.CharField(choices=[('purchase', 'Purchase'), ('trade', 'Trade')], max_length=20)),
                ('purchase_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to=settings.AUTH_USER_MODEL)),
                ('teaching_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='skills.teachingclass')),
            ],
            options={
                'unique_together': {('user', 'teaching_class')},
            },
        ),
    ]
