# Generated by Django 5.2.7 on 2025-10-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_teacherapplication_teachingclass_classtradeoffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_applications/'),
        ),
    ]
