# Generated by Django 5.2.7 on 2025-10-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_teacherapplication_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='is_tradeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='price_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
