# Generated by Django 5.2.7 on 2025-11-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_swipeaction'),
        ('skills', '0005_teacherapplication_difficulty_and_more'),
    ]

    operations = [
    ]
