# Generated by Django 5.2.7 on 2025-11-13 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_swipeaction_teaching_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When this time slot starts')),
                ('end_time', models.DateTimeField(help_text='When this time slot ends')),
                ('max_students', models.PositiveIntegerField(default=1, help_text='Maximum number of students for this slot')),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring slot?')),
                ('recurrence_pattern', models.CharField(blank=True, help_text='e.g., "weekly", "daily", "MWF" for recurring slots', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this time slot')),
                ('is_active', models.BooleanField(default=True, help_text='Is this slot currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teaching_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='skills.teachingclass')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Student notes or special requests')),
                ('teacher_notes', models.TextField(blank=True, help_text='Teacher notes (private)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(help_text='The enrollment that grants access to this booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='skills.classenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='skills.classtimeslot')),
            ],
            options={
                'ordering': ['time_slot__start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='classtimeslot',
            index=models.Index(fields=['teaching_class', 'start_time'], name='skills_clas_teachin_16324e_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimeslot',
            index=models.Index(fields=['start_time', 'is_active'], name='skills_clas_start_t_f4bd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='classbooking',
            index=models.Index(fields=['student', 'status'], name='skills_clas_student_dc081d_idx'),
        ),
        migrations.AddIndex(
            model_name='classbooking',
            index=models.Index(fields=['time_slot', 'status'], name='skills_clas_time_sl_43b59e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together={('time_slot', 'student')},
        ),
    ]
