# Generated by Django 5.2.7 on 2025-11-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_classfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingclass',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
